Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
for n in range(4):
    rf_phase = rf_phases()
    encoding, header = encoding_plan()
    print(f"RF phase: {rf_phase} [rad]")
    print(f"Gy amplitude (wrt to peak of gradient waveform): {encoding.gy_amp}")
    print(f"Phase encoding index: {header.iy}")
    print(f"RF frequency offset: {encoding.rf_freq}")
    print(f"Slice index: {header.iz}")
------------------

----- stdout -----
RF phase: 0.0 [rad]
Gy amplitude (wrt to peak of gradient waveform): -0.5
Phase encoding index: 0
RF frequency offset: 0.0
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[9], line 8[0m
[1;32m      6[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mPhase encoding index: [39m[38;5;132;01m{[39;00mheader[38;5;241m.[39miy[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m      7[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mRF frequency offset: [39m[38;5;132;01m{[39;00mencoding[38;5;241m.[39mrf_freq[38;5;132;01m}[39;00m[38;5;124m"[39m)
[0;32m----> 8[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mSlice index: [39m[38;5;132;01m{[39;00m[43mheader[49m[38;5;241;43m.[39;49m[43miz[49m[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mAttributeError[0m: 'types.SimpleNamespace' object has no attribute 'iz'

